name: Auto-Assign Based on Dropdown

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign if dropdown = Yes
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            const user = context.payload.issue.user.login;

            // Match the question + answer block
            const match = body.match(/### Would you like to work on this issue\?\s*\n\s*(.*)/i);
            const answer = match ? match[1].trim().toLowerCase() : "";
            const today = new Date().toISOString().split('T')[0];

            console.log("Parsed dropdown answer:", answer);

            if (answer === "yes") {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [user],
              });
              
              await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: `[Assigned on] ${today}`
              });
            console.log(`✅ Assigned @${user}`);
            } else {
              console.log("❌ Not assigning — answer was:", answer);
            }
