name: Auto-Assign
on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
  issue_comment:
    types: [created]

permissions:
  issues: write

jobs:
  assign-based-on-template-or-command:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request == null
    steps:
      - name: Check for 'Yes' in issue template response
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || "";
            if (body.includes("### Would you like to work on this issue?") && body.includes("Yes")) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.payload.issue.user.login]
              });
            }

      - name: Check for "/assign" comment
        if: github.event_name == 'issue_comment'
        uses: actions/github-script@v7
        with:
          script: |
            const comment = context.payload.comment.body;
            const issue = context.payload.issue;
            if (comment.trim() === '/assign' && issue.assignees.length < 2) {
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                assignees: [context.payload.comment.user.login]
              });
              }
